services:
  postgres:
    image: postgres:latest
    container_name: oca42
    environment:
      POSTGRES_DB: oca42
      POSTGRES_USER: db
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    #    networks:
    #      - pg-network
    volumes:
      - pg-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pg-admin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
#    networks:
#      - pg-network
#
#networks:
#  pg-network:

volumes:
  pg-data: